
[general]
	disable_mod = false
	space_modules = false
	shadow_text = true
	animations = true
	animationSpeed = 1.0
	fontScale = 1.0
	background_color = 1867534416

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "graphics"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		render_distance = true
		graphics = true
		clouds = true
		biome_blend_radius = false
		shader = true

[[modules_left]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = false
		chunk_relative_coords = false
		chunk_coords = false

[[modules_left]]
	name = "chunks"
	name_color = 43775
	value_color = 16777045
	enabled = true

	[modules_left.lines]
		chunk_sections = false
		chunk_culling = false
		pending_chunks = false
		pending_uploads = false
		available_buffers = false
		client_chunk_cache = false
		loaded_chunks = true
		loaded_chunks_server = true
		forceloaded_chunks = false
		spawn_chunks = false

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = false
		rotation = false
		light = true
		light_server = true
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = true
		days_played = true

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		pie_graph = true
		fps_tps = true
		help = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "miscleft"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		misc_left = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		java_version = true
		memory_usage = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "miscright"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		misc_right = true

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = true
		id_block = true
		block_states = true
		block_tags = true
		blank = true
		targeted_fluid = true
		id_fluid = true
		fluid_states = true
		fluid_tags = true
		blank2 = true
		targeted_entity = true

